// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lumberman.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the log data
type LogRequest struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{0}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *LogRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// The response message containing status of saving log data
type LogReply struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogReply) Reset()         { *m = LogReply{} }
func (m *LogReply) String() string { return proto.CompactTextString(m) }
func (*LogReply) ProtoMessage()    {}
func (*LogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{1}
}

func (m *LogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogReply.Unmarshal(m, b)
}
func (m *LogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogReply.Marshal(b, m, deterministic)
}
func (m *LogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogReply.Merge(m, src)
}
func (m *LogReply) XXX_Size() int {
	return xxx_messageInfo_LogReply.Size(m)
}
func (m *LogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LogReply.DiscardUnknown(m)
}

var xxx_messageInfo_LogReply proto.InternalMessageInfo

func (m *LogReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// The request message containing the key
type GetLogRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogRequest) Reset()         { *m = GetLogRequest{} }
func (m *GetLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogRequest) ProtoMessage()    {}
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{2}
}

func (m *GetLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogRequest.Unmarshal(m, b)
}
func (m *GetLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogRequest.Marshal(b, m, deterministic)
}
func (m *GetLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogRequest.Merge(m, src)
}
func (m *GetLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogRequest.Size(m)
}
func (m *GetLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogRequest proto.InternalMessageInfo

func (m *GetLogRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// The response message containing the log data and timestamp
type GetLogReply struct {
	Key                  string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 string               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetLogReply) Reset()         { *m = GetLogReply{} }
func (m *GetLogReply) String() string { return proto.CompactTextString(m) }
func (*GetLogReply) ProtoMessage()    {}
func (*GetLogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{3}
}

func (m *GetLogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogReply.Unmarshal(m, b)
}
func (m *GetLogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogReply.Marshal(b, m, deterministic)
}
func (m *GetLogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogReply.Merge(m, src)
}
func (m *GetLogReply) XXX_Size() int {
	return xxx_messageInfo_GetLogReply.Size(m)
}
func (m *GetLogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogReply proto.InternalMessageInfo

func (m *GetLogReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetLogReply) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetLogReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// The request message containing the log prefix
type GetLogsRequest struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogsRequest) Reset()         { *m = GetLogsRequest{} }
func (m *GetLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogsRequest) ProtoMessage()    {}
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{4}
}

func (m *GetLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogsRequest.Unmarshal(m, b)
}
func (m *GetLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogsRequest.Merge(m, src)
}
func (m *GetLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogsRequest.Size(m)
}
func (m *GetLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogsRequest proto.InternalMessageInfo

func (m *GetLogsRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// The response message containing the logs for prefix
type GetLogsReply struct {
	Logs                 []*GetLogReply `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetLogsReply) Reset()         { *m = GetLogsReply{} }
func (m *GetLogsReply) String() string { return proto.CompactTextString(m) }
func (*GetLogsReply) ProtoMessage()    {}
func (*GetLogsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{5}
}

func (m *GetLogsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogsReply.Unmarshal(m, b)
}
func (m *GetLogsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogsReply.Marshal(b, m, deterministic)
}
func (m *GetLogsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogsReply.Merge(m, src)
}
func (m *GetLogsReply) XXX_Size() int {
	return xxx_messageInfo_GetLogsReply.Size(m)
}
func (m *GetLogsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogsReply proto.InternalMessageInfo

func (m *GetLogsReply) GetLogs() []*GetLogReply {
	if m != nil {
		return m.Logs
	}
	return nil
}

// The response message containing all prefixes
type ListPrefixesReply struct {
	Prefixes             []string `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPrefixesReply) Reset()         { *m = ListPrefixesReply{} }
func (m *ListPrefixesReply) String() string { return proto.CompactTextString(m) }
func (*ListPrefixesReply) ProtoMessage()    {}
func (*ListPrefixesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{6}
}

func (m *ListPrefixesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPrefixesReply.Unmarshal(m, b)
}
func (m *ListPrefixesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPrefixesReply.Marshal(b, m, deterministic)
}
func (m *ListPrefixesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPrefixesReply.Merge(m, src)
}
func (m *ListPrefixesReply) XXX_Size() int {
	return xxx_messageInfo_ListPrefixesReply.Size(m)
}
func (m *ListPrefixesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPrefixesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListPrefixesReply proto.InternalMessageInfo

func (m *ListPrefixesReply) GetPrefixes() []string {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

// The request message containing all keys by prefix
type ListLogsRequest struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLogsRequest) Reset()         { *m = ListLogsRequest{} }
func (m *ListLogsRequest) String() string { return proto.CompactTextString(m) }
func (*ListLogsRequest) ProtoMessage()    {}
func (*ListLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{7}
}

func (m *ListLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLogsRequest.Unmarshal(m, b)
}
func (m *ListLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLogsRequest.Marshal(b, m, deterministic)
}
func (m *ListLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLogsRequest.Merge(m, src)
}
func (m *ListLogsRequest) XXX_Size() int {
	return xxx_messageInfo_ListLogsRequest.Size(m)
}
func (m *ListLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLogsRequest proto.InternalMessageInfo

func (m *ListLogsRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// The response message containing the keys for prefix
type ListLogsReply struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLogsReply) Reset()         { *m = ListLogsReply{} }
func (m *ListLogsReply) String() string { return proto.CompactTextString(m) }
func (*ListLogsReply) ProtoMessage()    {}
func (*ListLogsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c351de099da60036, []int{8}
}

func (m *ListLogsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLogsReply.Unmarshal(m, b)
}
func (m *ListLogsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLogsReply.Marshal(b, m, deterministic)
}
func (m *ListLogsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLogsReply.Merge(m, src)
}
func (m *ListLogsReply) XXX_Size() int {
	return xxx_messageInfo_ListLogsReply.Size(m)
}
func (m *ListLogsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLogsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListLogsReply proto.InternalMessageInfo

func (m *ListLogsReply) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*LogRequest)(nil), "pb.LogRequest")
	proto.RegisterType((*LogReply)(nil), "pb.LogReply")
	proto.RegisterType((*GetLogRequest)(nil), "pb.GetLogRequest")
	proto.RegisterType((*GetLogReply)(nil), "pb.GetLogReply")
	proto.RegisterType((*GetLogsRequest)(nil), "pb.GetLogsRequest")
	proto.RegisterType((*GetLogsReply)(nil), "pb.GetLogsReply")
	proto.RegisterType((*ListPrefixesReply)(nil), "pb.ListPrefixesReply")
	proto.RegisterType((*ListLogsRequest)(nil), "pb.ListLogsRequest")
	proto.RegisterType((*ListLogsReply)(nil), "pb.ListLogsReply")
}

func init() { proto.RegisterFile("lumberman.proto", fileDescriptor_c351de099da60036) }

var fileDescriptor_c351de099da60036 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4b, 0x4b, 0xeb, 0x40,
	0x14, 0x6e, 0x1e, 0xe4, 0xb6, 0xa7, 0xef, 0x73, 0xb9, 0xa5, 0xe4, 0x5e, 0xb8, 0x75, 0x8a, 0x50,
	0x37, 0xa9, 0xb6, 0x0a, 0xdd, 0x09, 0x82, 0xb8, 0xc9, 0x42, 0xa2, 0x2b, 0x77, 0x09, 0x4e, 0x43,
	0x69, 0xe2, 0x8c, 0xc9, 0x14, 0xcc, 0xbf, 0xf3, 0xa7, 0x49, 0x26, 0xcf, 0xb6, 0x8a, 0xee, 0xce,
	0xe3, 0xfb, 0xce, 0xf9, 0xbe, 0x33, 0x03, 0xfd, 0x60, 0x17, 0x7a, 0x34, 0x0a, 0xdd, 0x17, 0x8b,
	0x47, 0x4c, 0x30, 0x54, 0xb9, 0x67, 0xfe, 0xf5, 0x19, 0xf3, 0x03, 0x3a, 0x97, 0x15, 0x6f, 0xb7,
	0x9e, 0xd3, 0x90, 0x8b, 0x24, 0x03, 0x98, 0xff, 0x0f, 0x9b, 0x62, 0x13, 0xd2, 0x58, 0xb8, 0x21,
	0xcf, 0x00, 0x64, 0x05, 0x60, 0x33, 0xdf, 0xa1, 0xaf, 0x3b, 0x1a, 0x0b, 0x1c, 0x81, 0xc1, 0x23,
	0xba, 0xde, 0xbc, 0x8d, 0x95, 0x89, 0x32, 0x6b, 0x39, 0x79, 0x86, 0x08, 0xfa, 0xb3, 0x2b, 0xdc,
	0xb1, 0x2a, 0xab, 0x32, 0x26, 0xff, 0xa0, 0x29, 0x99, 0x3c, 0x48, 0x70, 0x00, 0xda, 0x96, 0x26,
	0x39, 0x29, 0x0d, 0xc9, 0x09, 0x74, 0xef, 0xa8, 0xa8, 0x8d, 0x3e, 0x86, 0x84, 0xd0, 0x2e, 0x20,
	0x9f, 0xce, 0xc0, 0x15, 0xb4, 0x4a, 0xb9, 0x72, 0x75, 0x7b, 0x61, 0x5a, 0x99, 0x21, 0xab, 0x30,
	0x64, 0x3d, 0x16, 0x08, 0xa7, 0x02, 0x97, 0x7a, 0xb5, 0x9a, 0xde, 0x19, 0xf4, 0xb2, 0x75, 0xf1,
	0x37, 0x6e, 0xc9, 0x12, 0x3a, 0x25, 0x32, 0x55, 0x36, 0x05, 0x3d, 0x60, 0x7e, 0x3c, 0x56, 0x26,
	0xda, 0xac, 0xbd, 0xe8, 0x5b, 0xdc, 0xb3, 0x6a, 0xc2, 0x1d, 0xd9, 0x24, 0x73, 0x18, 0xda, 0x9b,
	0x58, 0xdc, 0xcb, 0x11, 0x34, 0x67, 0x9a, 0xd0, 0xe4, 0x79, 0x41, 0xb2, 0x5b, 0x4e, 0x99, 0x93,
	0x33, 0xe8, 0xa7, 0x84, 0x9f, 0x08, 0x9a, 0x42, 0xb7, 0x82, 0xa6, 0x73, 0x11, 0xf4, 0x2d, 0x4d,
	0x8a, 0x99, 0x32, 0x5e, 0xbc, 0xab, 0x60, 0xd8, 0xcc, 0xf7, 0x69, 0x84, 0xa7, 0xa0, 0xd9, 0xcc,
	0xc7, 0x5e, 0xaa, 0xb4, 0x7a, 0x02, 0xb3, 0x53, 0xe6, 0x3c, 0x48, 0x48, 0x03, 0x2d, 0x30, 0x32,
	0x1f, 0x38, 0xac, 0x7b, 0xca, 0xc0, 0x87, 0x36, 0x49, 0x03, 0x2f, 0xe0, 0x57, 0x7e, 0x17, 0xc4,
	0xaa, 0x5b, 0xa8, 0x37, 0x07, 0x7b, 0xb5, 0x8c, 0x72, 0x05, 0xf0, 0x20, 0x22, 0xea, 0x86, 0x5f,
	0xb2, 0x8e, 0xf7, 0x9c, 0x2b, 0x78, 0x0d, 0x9d, 0xfa, 0x31, 0x71, 0x74, 0xf4, 0xec, 0xb7, 0xe9,
	0x27, 0x37, 0xff, 0x48, 0x47, 0x87, 0x67, 0x27, 0x0d, 0xbc, 0x84, 0x66, 0x71, 0x31, 0xfc, 0x5d,
	0x80, 0xea, 0x6b, 0x87, 0xfb, 0x45, 0xc9, 0xba, 0xd1, 0x9f, 0x54, 0xee, 0x79, 0x86, 0x5c, 0xb2,
	0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xbf, 0xa1, 0xf4, 0x6e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	// Write to Log
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error)
	// Get Log by key
	GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogReply, error)
	// Get all Logs by prefix
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsReply, error)
	// Stream Logs by prefix
	StreamLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (Logger_StreamLogsClient, error)
	// List Log prefixes
	ListPrefixes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPrefixesReply, error)
	// List Log keys by prefix
	ListLogs(ctx context.Context, in *ListLogsRequest, opts ...grpc.CallOption) (*ListLogsReply, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error) {
	out := new(LogReply)
	err := c.cc.Invoke(ctx, "/pb.Logger/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogReply, error) {
	out := new(GetLogReply)
	err := c.cc.Invoke(ctx, "/pb.Logger/GetLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsReply, error) {
	out := new(GetLogsReply)
	err := c.cc.Invoke(ctx, "/pb.Logger/GetLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) StreamLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (Logger_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Logger_serviceDesc.Streams[0], "/pb.Logger/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &loggerStreamLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Logger_StreamLogsClient interface {
	Recv() (*GetLogReply, error)
	grpc.ClientStream
}

type loggerStreamLogsClient struct {
	grpc.ClientStream
}

func (x *loggerStreamLogsClient) Recv() (*GetLogReply, error) {
	m := new(GetLogReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggerClient) ListPrefixes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPrefixesReply, error) {
	out := new(ListPrefixesReply)
	err := c.cc.Invoke(ctx, "/pb.Logger/ListPrefixes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) ListLogs(ctx context.Context, in *ListLogsRequest, opts ...grpc.CallOption) (*ListLogsReply, error) {
	out := new(ListLogsReply)
	err := c.cc.Invoke(ctx, "/pb.Logger/ListLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	// Write to Log
	Log(context.Context, *LogRequest) (*LogReply, error)
	// Get Log by key
	GetLog(context.Context, *GetLogRequest) (*GetLogReply, error)
	// Get all Logs by prefix
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsReply, error)
	// Stream Logs by prefix
	StreamLogs(*GetLogsRequest, Logger_StreamLogsServer) error
	// List Log prefixes
	ListPrefixes(context.Context, *empty.Empty) (*ListPrefixesReply, error)
	// List Log keys by prefix
	ListLogs(context.Context, *ListLogsRequest) (*ListLogsReply, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) Log(ctx context.Context, req *LogRequest) (*LogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (*UnimplementedLoggerServer) GetLog(ctx context.Context, req *GetLogRequest) (*GetLogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLog not implemented")
}
func (*UnimplementedLoggerServer) GetLogs(ctx context.Context, req *GetLogsRequest) (*GetLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (*UnimplementedLoggerServer) StreamLogs(req *GetLogsRequest, srv Logger_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (*UnimplementedLoggerServer) ListPrefixes(ctx context.Context, req *empty.Empty) (*ListPrefixesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrefixes not implemented")
}
func (*UnimplementedLoggerServer) ListLogs(ctx context.Context, req *ListLogsRequest) (*ListLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLogs not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Logger/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Logger/GetLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).GetLog(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Logger/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggerServer).StreamLogs(m, &loggerStreamLogsServer{stream})
}

type Logger_StreamLogsServer interface {
	Send(*GetLogReply) error
	grpc.ServerStream
}

type loggerStreamLogsServer struct {
	grpc.ServerStream
}

func (x *loggerStreamLogsServer) Send(m *GetLogReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Logger_ListPrefixes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).ListPrefixes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Logger/ListPrefixes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).ListPrefixes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_ListLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).ListLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Logger/ListLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).ListLogs(ctx, req.(*ListLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _Logger_Log_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _Logger_GetLog_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _Logger_GetLogs_Handler,
		},
		{
			MethodName: "ListPrefixes",
			Handler:    _Logger_ListPrefixes_Handler,
		},
		{
			MethodName: "ListLogs",
			Handler:    _Logger_ListLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Logger_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lumberman.proto",
}
